---
output: pdf_document
---

Cover letter, containing:

<!-- The title of the paper and a statement of its main point -->

<!-- Any information needed to ensure a fair review process, including related manuscripts submitted to other journals -->

<!-- Names of colleagues who have reviewed the paper -->

<!-- A statement that none of the material has been published or is under consideration elsewhere, including the Internet. -->

<!-- Names, telephone, and e-mail addresses for all authors, including selection of one to be corresponding author. -->


Dr. Ali Shilatifard                        03-06-2020
Editor, *Science Advances*


We recommend our paper to be handled by Deputy Editor Dr. Jeremy Jackson and Associate Editor Dr. Jennifer Jacquet and suggest the following reviewers: 

<!-- Names, affiliations, and e-mail addresses of five potential referees. -->
-
- Gretta Pecl, 
- Rebecca Selden, Wellesley College, Wellesley, MA, USA; bselden@wellesley.edu  
- 
- 


This manuscript is not being considered for publication in any other journal. All data will be available upon request and the code used to analyze the data can be found at https://github.com/jepa/SharedToE All contributing authors and institutions have been identified, and the authors have no competing financial interests. This manuscript has been reviewed and approved by all authors.

Thank you for your consideration of this submission.
Sincerely (on behalf of all authors),



Juliano Palacios Abrantes  
The Institute for Oceans and Fisheries  
The University of British Columbia