---
title: "Response to Reviewer One"
# output: pdf_document
output: word_document
---

# Main comment 

I appreciated the opportunity to review “Imminent range shifts in transboundary fish stocks challenge their management under climate change.” The figures were quite informative and visually pleasing so I comment the authors on this effect. I had only two large scale questions or concerns the first of which was more related to the policy-side raised in the abstract. **Specifically thinking how many bilateral agreements exist, and which ones should be considered “ready” for addressing transboundary shifts ** In addition, **the issue of model-specific variance is not represented in the manuscript**. Variance as a topic is well discussed in the discussion but I am left wanting to know the error bounds around some of the numbers presented (# of stocks shifting, net gain / loss of stocks by EEZ, years of response as well). I think if these two concerns can be addressed, the manuscript would be of great interest to a wide audience. I have some finer scale points raised below as well.

- **Response:** Thank you very much for commenting on our figures. Here, we provide responses to the two large scale questions you provide and below we respond the finer scale points. We hope that this clarifies all of your comments. 

 - **Regarding the bi-lateral agreements**, this is a great question that, unfortunately, we cannot respond at this moment. Currently, there is only one database on bi-lateral agreements produce by Oremus *et al* (2020). On their paper, the authors state "we analysed 127 publicly available international fisheries agreements in the South Pacific, Southeast Asia, South Asia, Northwest Africa, and Central America and the Caribbean" and " For each agreement, we recorded the following information... If relevant, to which specific stock or species the agreement pertained". We contacted Dr. (Kimberly) Oremus who provided the provided the mentioned dataset. However, non of the 127 treaties have identified subjects at the species level (except for bigeye, skipjack and yellowtail tunas).

We hope that the reviewer understands the complexity of building such database and that this exercise falls outside the scope and stage of our current analysis. We agree that having such information would increase the manuscript impact, but, would not necessarily directly impact our results nor the message we want to covein (Ultimately Oremus *et at* state it very clearly in their paper, "None of the 127 agreements contains language that is directly related to climate change, range shifts or stock exits").

 - Oremus KL, Bone J, Costello C, Molinos JG, Lee A, Mangin T, Salzman J. 2020. Governance challenges for tropical nations losing fish species due to climate change. Nature Sustainability 6:1–4. Nature Publishing Group.

 - **Regarding model-specific variance.** For this paper we used one climate model (the GFDL) forced following one climate change scenario (RCP 8.5) to couple with one species distribution model. For this reason, providing quantitative upper and lower bounds of our results is not possible and would require substantial extra computation. However, because we have 10 different runs of the GFDL and employ the time of emergence concept, we are capable of providing a less conservative estimate of the numbers you mention (i.e., the number of shifting stocks and EEZs). This was originally presented in the methods section as a sensitivity analysis and has now been moved to the Methods section of the main paper (**NOTE TO CO-AUTHORS**: Should we include this in the results or leave it in the methods?). It reads on line *XXX* of page *XX*: *We also computed a less conservative estimation of shifting transboundary stocks by including a threshold of one standard deviation (i.e., representing a probability of 68% that the stock had shifted from natural variation; see methods). In this case, the global average shift in the shared distribution of transboundary stocks is 2029 $\pm$ 27 years, a difference of about 7 years (Fig. S8). In total, 5,745 transboundary stocks would shift their shared distributions between 2006 and 2100 considering a less conservative metric, that is, 33% (n = 1626) more shifting stocks (Figs. S2 and S8).*


P1L12 – “between neighbouring countries” – Is this not redundant with “transboundary?” Are you only examining stocks that currently cross jurisdictional boundaries? After further reading / review, it seems like this delineation would be useful to make explicit in the abstract.

- **Response:** Yes, "transboundary between neighboring countries” is indeed redundant. We have modified the manuscript to say "*Climate change is shifting the distribution of shared fish stocks between neighboring countries (transboundary).*" We believe it is important to keep both parts of the sentence for clarification.


P1L17-18 – which countries? Include specifics.

- **Response:** We are very limited in terms of word counting in the abstract so unfortunately, we cannot include specifics here. Please note that we do provide some in-text examples in the results section, specifically the revised Figure 4.

P2L1 – “Bi and multi” Also, some examples already exist and would be good to discuss as those that are particularly successful vs. those that aren’t.

- **Response:** Similarly, we do not have space to discuss this here. Please note that we discuss management plans on the paragraph starting on line *13* of page *12*.

P2L5 – I would say preferences for discrete environmental conditions are a proxy for factors that influence species distribution not as you’ve laid out here.

- **Response:** We have changed this sentence to *Marine species’ distributions mainly reflect species’ preferences for discrete environmental conditions (2).*

P4L3 – “633 transboundary fish species globally, representing 67% of identified exploited taxa.” – how many of these have bi-lateral agreements as well?

- **Response:** Please see the main comment response above. 

P5L7 – “Our results suggest that 4,119 transboundary stocks will experience a range shift beyond historical variability as early as 2006 and up to 2100 (Fig. 1A).” This is confusing as written. I would suggest “Our results suggest that 4,119 transboundary stocks will experience a range shift beyond historical variability by 2100 (hereafter referred to as ‘shifts’; Fig. 1A), with the first anomaly occurring as early as 2006.” if meaning is correct.

- **Response:** Thank you for the input, we have made the suggested change. 

P5L8 – “as early as 2006” is there a way to validate the historical period of these predictions (e.g. 2006-2020) to see if the model is actually predicting observed changes in transboundary stocks? This would greatly improve the validity of the manuscript.

- **Response:** In the section "High present-day climate risk of on transboundary fisheries management" we describe early shifts in the shared distribution of transboundary stocks including the cases of Humboldt squid (*Dosidicus gigas*) and Atlantic mackerel (*Scomber scombrus*) both in the early 2000s and have included a couple more punctual examples of documented shifts between 2006 and 2021. However, there is not a vast documentation on shifts in the distribution of transboundary species (i.e., specifically from one EEZ to another). Mapping these shifts is out of the scope of the current project as there is an ongoing effort to document the global hifts of transboundary species. 

P8L6 – can you include information on direction here as well? Are these top five countries gaining stocks, losing stocks or just shifting stocks? It would be good to know which countries are predicted to be winners vs. losers.

- **Response:** Thank you for your comment. We provide direction of change in the next figure (Figure 5 of the revised manuscript) showing winners and losers according to neighboring EEZs. Here we show how each neighboring EEZ will stand to win or lose against its neighbors. **NOTE FOR CO-AUTHORS:** *I am hesitant of actually pointing out winners and losers (e.g., stating that Spain will loos most of its catch to France). Hence, I rather leave the results and discussion more general. Thoughts?*

P9L7-8 – “catch proportion are expected to become more common and intense” – this sentence is a bit too jargon-y for the non-fisheries reader. Please specify whether you’re referring to increased specialization? Or?

- **Response:** We have modified this sentence in the revised manuscript with the hopes to make it less jargon-y. It now reeds on line *7* of *P9* the revised manuscript: "*There will be an increase in the number of stocks changing their catch proportion and the number of EEZs with changing stocks towards the mid-21st century. Such increase will be followed by an also increase in the intensity of the proportion change (Figs. S3 and S4).*" 

P10L6-7 – “with higher gains identified in warmer colors” Please be specific here on the scale as well. Which colors represent which # of stocks transitioning? This could be absolute number (stocks gained – stocks leaving) or relative (stocks gained – stocks leaving) / historical EEZ stocks. Both of these metrics could be quite useful for future planning.

- **Response:** We realize the figure was missing the legend and color bar making it confusing for the reader. We have now included the legend explaining the legend and color bar.

P12L2-3 – “As transboundary stocks continue to shift, such international disputes are likely to increase in frequency and requiring a revision of management plans (9, 28).” I do not disagree with this statement but it rings a bit hollow without knowing which country management plans need revision. I am not asking the authors to fully assess this literature but instead provide examples of successful management plans in response to transboundary shifts and examples those that are existing that would need to be revised.

- **Response:** Thank you for this comment. We have edited the paragraph starting at line **13** of page **12** to reflect this comment. 

Pgs 12-13 deal with this a bit but this could use more context.

- **Response:** Please see previous comment.

P13L10-12 – “Results from multiple marine ecosystem models show that SST and primary production (NPP) are the main drivers of changes in species distributions across oceanic basins (37, 38).” This statement is misleading in my opinion. They are often important drivers in our models but this may be in part because we don’t measure other metrics at the appropriate scale for global or basin-scale modeling. I would revise to say “are the main indicators of species distributional changes across ocean basins.”

- **Response:** Thank you for highlighting this. We have changed the sentence to reflect this comment.

P14L14-16 - “Overall, changes in fish biomass with multiple upper trophic level models show overall agreement across models in terms of direction of change, but vary in the magnitude of that change (38).” I really appreciate the discussion of uncertainty but it seems important to present uncertainty for the models you have presented as well. Is there an upper and lower bounds (based on RCP8.5) due to model uncertainty from the predictions you have included? This could be incorporated in a number of the presented data points, e.g. 4,119 stocks by 2100, 239 of the world EEZs, etc.

- **Response:**  Please see the response to the main comment above. 

P14L20-23 – “While this method might define some stocks that do not necessarily align with biologically-defined sub-populations within an EEZ, in many EEZs, fisheries are often managed at the species level (43) and sub-populations are potentially interconnected (44), thus, providing additional ecological ground for our analysis (45).” A counterpoint would argue that subpopulations may have different ecological responses to climate variability and change thus species-specific models may miss this nuance. You get to this topic a bit on the next page though.

- **Response:** We agree with this comment. However, based on the data available we are unable to increase the detail of our study.